---
# maintains ports, bianry or repo urls

org: encapsulate
domain_regex: ^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$
monitor_server_dns: monitor.encapsulate.xyz
ansible_port: 8192

architecture_map:
  x86_64: amd64
  aarch64: arm64

default_node_types:
  - validator
  - default

tmp_dir: /tmp

iota:
  file_extension: tgz
  validator:
    source_url: https://github.com/iotaledger/iota/releases/download
    ports:
      prefix: 81
      suffix:
        admin_interface: 37
        network_address: 80
        consensus_address: 81
        p2p: 84
        json_rpc: 01
        metrics: 85
  ssfn:
    source_url: https://github.com/iotaledger/iota/releases/download
    ports:
      admin_interface_port: 1338
      p2p_port: 8094
      json_rpc_port: 9001
      metrics_port: 9185
