---
# maintains ports, bianry or repo urls

org: encapsulate
domain_regex: ^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$
monitor_server_dns: monitor.encapsulate.xyz
ansible_port: 8192

architecture_map:
  x86_64: amd64
  aarch64: arm64

default_node_types:
  - validator
  - default

tmp_dir: /tmp

iota:
  file_extension: tgz
  validator:
    source_url: https://github.com/iotaledger/iota/releases/download
    ports:
      admin_interface_port: 1337
      network_address_port: 8080
      narwhal_primary_interface_port: 8081
      narwhal_worker_interface_port: 8082
      consensus_address_port: 8083
      p2p_port: 8084
      json_rpc_port: 9000
      metrics_port: 9184
  ssfn:
    source_url: https://github.com/iotaledger/iota/releases/download
    ports:
      admin_interface_port: 1338
      p2p_port: 8094
      json_rpc_port: 9001
      metrics_port: 9185
