---
# maintains ports, bianry or repo urls

org: encapsulate
domain_regex: ^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$
monitor_server_dns: monitor.encapsulate.xyz
ansible_port: 8192

architecture_map:
  x86_64: amd64
  aarch64: arm64

default_node_types:
  - validator
  - default

tmp_dir: /tmp

iota:
  file_extension: tgz
  validator:
    source_url: https://github.com/iotaledger/iota/releases/download
    secret_source_url: https://dbfiles.mainnet.iota.cafe
    ports:
      prefix: 81
      suffix:
        admin: 37
        network: 80
        # Consensus port is updated through onchain transcation, After every epoch it reads onchain 
        # data and updates the port.
        consensus: 81
        p2p: 84
        rpc: 90
        metrics: 91
  ssfn:
    source_url: https://github.com/iotaledger/iota/releases/download
    ports:
      admin_port: 1338
      p2p_port: 8094
      rpc_port: 9001
      metrics_port: 9185
