---
# maintains versions and can overwrite all.yml
iota:
  validator:
    version: v1.0.0
    external_address: validator.iota.mainnet.encapsulate.xyz
  ssfn:
    version: v1.0.0
    external_address: ssfn.iota.mainnet.encapsulate.xyz
  migration_blob_url: https://dbfiles.mainnet.iota.cafe/migration.blob
