---
node_ufw_rules:
  validator:
    - port: "{{ p2p_port }}"
      proto: udp
      rule: allow
      from: any
      comment: p2p_port

    - port: "{{ network_port }}"
      proto: tcp
      rule: allow
      from: any
      comment: network_port

    - port: "{{ consensus_port }}"
      proto: tcp
      rule: allow
      from: any
      comment: consensus_port

    - port: "{{ metrics_port }}"
      proto: tcp
      rule: allow
      from: "{{ monitor_server_dns }}"
      comment: metrics_port

  ssfn:
    - port: "{{ iota.ssfn.ports.p2p_port }}"
      proto: udp
      rule: allow
      from: any
      comment: p2p_port

    - port: "{{ iota.ssfn.ports.metrics_port }}"
      proto: tcp
      rule: allow
      from: "{{ monitor_server_dns }}"
      comment: metrics_port
