---
node_ufw_rules:
  validator:
    - port: "{{ iota.validator.ports.p2p_port }}"
      proto: udp
      rule: allow
      from: any
      comment: p2p_port

    - port: "{{ iota.validator.ports.network_address_port }}"
      proto: tcp
      rule: allow
      from: any
      comment: network_address_port

    - port: "{{ iota.validator.ports.consensus_address_port }}"
      proto: tcp
      rule: allow
      from: any
      comment: consensus_address_port

    - port: "{{ iota.validator.ports.metrics_port }}"
      proto: tcp
      rule: allow
      from: "{{ monitor_server_dns }}"
      comment: metrics_port

  ssfn:
    - port: "{{ iota.ssfn.ports.p2p_port }}"
      proto: udp
      rule: allow
      from: any
      comment: p2p_port

    - port: "{{ iota.ssfn.ports.metrics_port }}"
      proto: tcp
      rule: allow
      from: "{{ monitor_server_dns }}"
      comment: metrics_port
