---
snapshot_sync_genesis_file_name: genesis.blob

snapshot_sync_tool_default_binary_name: iota-tool

snapshot_sync_env_vars:
  MAINNET_FORMAL_UNSIGNED_BUCKET: "{{ iota.unsigned_bucket_name }}"
  AWS_SNAPSHOT_ENDPOINT: "{{ iota.aws_snapshot_endpoint }}"
  FORMAL_SNAPSHOT_ARCHIVE_BUCKET: "{{ iota.archive_bucket_name }}"
  AWS_ARCHIVE_ENDPOINT: "{{ iota.aws_archive_endpoint }}"
  AWS_ARCHIVE_VIRTUAL_HOSTED_REQUESTS: "true"
