---
# maintains mainnet inventory grouped by project names
all:
  vars:
    env: mainnet
  children:
    iota:
      hosts:
        ts.validator.iota.mainnet.encapsulate.xyz:
          type: validator
        ts.ssfn.iota.mainnet.encapsulate.xyz:
          type: ssfn
