---
# maintains testnet inventory grouped by project names
all:
  vars:
    env: testnet
  children:
    iota:
      hosts:
        ts.validator.iota.testnet.encapsulate.xyz:
          type: validator
        ts.ssfn.iota.testnet.encapsulate.xyz:
          type: ssfn
