---
# maintains testnet inventory grouped by project names
all:
  vars:
    env: testnet
  children:
    iota:
      hosts:
        validator.iota.testnet.encapsulate.xyz:
          type: validator
        fullnode.iota.testnet.encapsulate.xyz:
          type: fullnode
