---
- name: Configure sysctl settings for node
  ansible.builtin.copy:
    dest: "/etc/sysctl.d/100-{{ service_identifier }}.conf"
    content: |
      net.core.rmem_max = 104857600
      net.core.wmem_max = 104857600
      net.ipv4.tcp_rmem = 8192 262144 104857600
      net.ipv4.tcp_wmem = 8192 262144 104857600
    owner: root
    group: root
    mode: "0644"
  register: sysctl_settings

- name: Apply sysctl settings
  ansible.builtin.command: sysctl --system
  when: sysctl_settings.changed
