---
- name: Create a directory with specific permissions and ownership
  ansible.builtin.file:
    path: "{{ tmp_dir }}/{{ service_identifier }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Download and unzip
  ansible.builtin.unarchive:
    src: "{{ iota[type].secret_source_url }}/iota-releases-iota-{{ iota[type].version }}-release-linux-x86_64.zip"
    dest: "{{ tmp_dir }}/{{ service_identifier }}"
    remote_src: true
    owner: root
    group: root
    mode: "0755"

- name: Download and unarchive
  ansible.builtin.unarchive:
    src: "{{ tmp_dir }}/{{ service_identifier }}/iota-releases-iota-{{ iota[type].version }}-release-linux-x86_64.tgz"
    dest: "{{ tmp_dir }}/{{ service_identifier }}"
    remote_src: true
    owner: root
    group: root
    mode: "0755"

- name: Copy the binary file
  ansible.builtin.copy:
    src: "{{ tmp_dir }}/{{ service_identifier }}/{{ item.extracted_path }}"
    dest: "{{ item.dest_path }}"
    remote_src: true
    owner: root
    group: root
    force: true
    mode: "0755"
  with_items: "{{ path_mapping }}"
  notify:
    - Restart service

- name: Clean up the temporary files in /tmp
  ansible.builtin.file:
    path: "{{ tmp_dir }}/{{ service_identifier }}"
    state: absent
